library(tidyverse)
library(ggplot2)
library(dplyr)
pdf("visualization.pdf")
df <- read.csv("Suicide Deaths by Age.csv")
Age <- df$Age
Suicides <- df$Suicides
plot(Age,Suicides,main= "Correlation of suicides and age of 18 to 95 ", xlim = c(18,95),col = "lightblue",ylim = c(0,200),xlab = "Ages(18 to 95)")
model <- lm(Suicides ~ Age, data = df) 
abline(model, col = "blue")
h = hist(Suicides,main = "Histogram of Suicides", xlab = "Suicides",col = "grey")
xfit=seq(min(Suicides), max(Suicides) , length = 10)
yfit = dnorm(xfit,mean = mean(Suicides), sd=sd(Suicides))
yfit = yfit*diff(h$mids[1:2]*length(Suicides))
lines(xfit,yfit, col = " red " , lwd = 2)
dev.off()